services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=DBPockOData
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
  application:
    image: pockodata1
    container_name: odata_api
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - database
